[relaychain]
default_image = "docker.io/parity/polkadot:latest"
default_command = "polkadot"
default_args = ["-lparachain=debug"]

chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 100
chain = "asset-hub-polkadot-local"

  [parachains.collator]
  name = "collator01"
  image = "docker.io/parity/polkadot-parachain:latest"
  ws_port = 42069
  command = "polkadot-parachain"
  args = ["-lparachain=debug"]
  